import os
import subprocess
import shutil
import sys
import textwrap

APP_NAME = "WSL COM Manager"
VERSION = "1.0.0"
SCRIPT_FILE = "wsl_com_manager.py"
ICON_FILE = "title.ico"
PNG_FILE = "title.png"


# ---------------------------------------------------------
# Helper: Run a command with visible output
# ---------------------------------------------------------
def run(cmd):
    print(f"\n>>> {cmd}")
    result = subprocess.run(cmd, shell=True)
    if result.returncode != 0:
        print(f"Command failed: {cmd}")
        sys.exit(1)


# ---------------------------------------------------------
# 1. Clean old build directories
# ---------------------------------------------------------
def clean_old():
    for folder in ("build", "dist"):
        if os.path.exists(folder):
            shutil.rmtree(folder)
    print("[✓] Old build cleaned")


# ---------------------------------------------------------
# 2. Build EXE using PyInstaller
# ---------------------------------------------------------
def build_exe():
    cmd = (
        f'pyinstaller --noconsole --onefile --windowed '
        f'--name "{APP_NAME}" '
        f'--icon "{ICON_FILE}" '
        f'--add-data "{PNG_FILE};." '
        f'{SCRIPT_FILE}'
    )
    run(cmd)
    print("[✓] EXE build complete")


# ---------------------------------------------------------
# 3. Generate Inno Setup installer script
# ---------------------------------------------------------
def generate_inno_script():
    iss_content = textwrap.dedent(f"""
        ; Auto-generated by build_installer.py

        [Setup]
        AppName={APP_NAME}
        AppVersion={VERSION}
        AppPublisher=Suhas KR
        DefaultDirName={{pf}}\\{APP_NAME}
        DefaultGroupName={APP_NAME}
        OutputDir=installer
        OutputBaseFilename=WSL COM Manager Setup
        SetupIconFile={ICON_FILE}
        Compression=lzma
        SolidCompression=yes
        WizardStyle=modern
        PrivilegesRequired=admin

        [Files]
        Source: "dist\\{APP_NAME}.exe"; DestDir: "{{app}}"; Flags: ignoreversion
        Source: "{PNG_FILE}"; DestDir: "{{app}}"; Flags: ignoreversion
        Source: "{ICON_FILE}"; DestDir: "{{app}}"; Flags: ignoreversion

        [Icons]
        Name: "{{group}}\\WSL COM Manager"; Filename: "{{app}}\\{APP_NAME}.exe"; IconFilename: "{{app}}\\{ICON_FILE}"
        Name: "{{userdesktop}}\\WSL COM Manager"; Filename: "{{app}}\\{APP_NAME}.exe"; IconFilename: "{{app}}\\{ICON_FILE}"

        [Run]
        Filename: "{{app}}\\{APP_NAME}.exe"; Description: "Launch application"; Flags: nowait postinstall
    """)

    script_path = "installer_script.iss"
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(iss_content)

    print(f"[✓] Inno Setup script generated: {script_path}")
    return script_path


# ---------------------------------------------------------
# 4. Compile installer using Inno Setup
# ---------------------------------------------------------
def build_installer(iss_file):
    # Ensure your path is correct
    inno_path = r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe"

    if not os.path.exists(inno_path):
        print("❌ ERROR: Inno Setup is not installed.")
        print("Download here: https://jrsoftware.org/isdl.php")
        sys.exit(1)

    run(f'"{inno_path}" "{iss_file}"')

    print("\n[✓] Installer created successfully!")
    print("Output → installer/WSL COM Manager Setup.exe")


# ---------------------------------------------------------
# MAIN
# ---------------------------------------------------------
if __name__ == "__main__":
    print("\n=== BUILD & INSTALLER AUTOMATION ===\n")

    clean_old()
    build_exe()
    iss_file = generate_inno_script()
    build_installer(iss_file)

    print("\n🎉 Done! Your installer is ready.\n")
